apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | default "checkoutservice" }}
  namespace: {{ .Values.namespace | default "checkoutservice" }}
  labels:
    {{- include "checkoutservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "checkoutservice.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "checkoutservice.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.name | default "checkoutservice" }}
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
          - containerPort: {{ .Values.service.targetPort }}
          env:
          {{- range .Values.env }}
          - name: {{ .name }}
            value: "{{ .value }}"
          {{- end }}
          readinessProbe:
            grpc:
              port: {{ .Values.service.targetPort }}
          livenessProbe:
            grpc:
              port: {{ .Values.service.targetPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}