apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | default "paymentservice" }}
  namespace: {{ .Values.namespace | default "paymentservice" }}
  labels:
    {{- include "paymentservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "paymentservice.labels" . | nindent 6 }}
  ports:
  - name: grpc
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}