apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  namespace: {{ .Values.namespace | default "cartservice" }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    {{- include "redis.labels" . | nindent 6 }}
  ports:
  - name: tcp-redis
    port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.targetPort }}