apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | default "emailservice" }}
  namespace: {{ .Values.namespace | default "emailservice" }}
  labels:
    {{- include "emailservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "emailservice.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "emailservice.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.name | default "emailservice" }}
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: "{{ .value }}"
        {{- end }}
        readinessProbe:
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          grpc:
            port: {{ .Values.readinessProbe.grpcPort }}
        livenessProbe:
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          grpc:
            port: {{ .Values.livenessProbe.grpcPort }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
