apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.service.labels.app }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.service.labels.app }}
  ports:
  - name: grpc
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
