# Default values for recommendationservice
#global
name: recommendationservice
namespace: recommendationservice

replicaCount: 1

image:
  repository: preranamauryaa/microservice-recommendationservice
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 220Mi
  limits:
    cpu: 200m
    memory: 450Mi

terminationGracePeriodSeconds: 5

env:
  - name: PORT
    value: "8080"
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice.productcatalogservice.svc.cluster.local:3550"
  - name: DISABLE_PROFILER
    value: "1"
