image:
  repository: preranamauryaa/microservice-frontendservice
  tag: latest

serviceAccount:
  name: frontend

deployment:
  name: frontend
  labels:
    app: frontend
  container:
    name: server
    imagePullPolicy: Always
    port: 8080
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  probes:
    readiness:
      initialDelaySeconds: 10
      httpGet:
        path: "/_healthz"
        port: 8080
        httpHeaders:
          - name: "Cookie"
            value: "shop_session-id=x-readiness-probe"
    liveness:
      initialDelaySeconds: 10
      httpGet:
        path: "/_healthz"
        port: 8080
        httpHeaders:
          - name: "Cookie"
            value: "shop_session-id=x-liveness-probe"

service:
  name: frontend
  labels:
    app: frontend
  type: ClusterIP
  port: 80
  targetPort: 8080

externalService:
  name: frontend-external
  labels:
    app: frontend
  type: LoadBalancer
  port: 80
  targetPort: 8080
