apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-canary
  namespace: {{ .Values.namespace | default "frontend" }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
    canary: {{ .Values.canary.labels.canary | quote }}
spec:
  selector:
    matchLabels:
      {{- include "frontend.labels" . | nindent 6 }}
      canary: {{ .Values.canary.labels.canary | quote }}
  template:
    metadata:
      labels:
        {{- include "frontend.labels" . | nindent 8 }}
        canary: {{ .Values.canary.labels.canary | quote }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: {{ .Values.name }}
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: "{{ .Values.canary.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.canary.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ports.targetPort }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.ports.targetPort }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.ports.targetPort }}
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
