apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-external
  namespace: {{ .Values.namespace | default "frontend" }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    {{- include "frontend.labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.ports.http }}
      targetPort: {{ .Values.ports.targetPort }}