image:
  repository: preranamauryaa/microservice-emailservice
  tag: newversion

serviceAccount:
  name: emailservice

namespace:
  name: emailservice

deployment:
  name: emailservice
  labels:
    app: emailservice
  container:
    name: server
    imagePullPolicy: Always
    port: 8080
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
  terminationGracePeriodSeconds: 5
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  readinessProbe:
    periodSeconds: 5
    grpc:
      port: 8080
  livenessProbe:
    periodSeconds: 5
    grpc:
      port: 8080

service:
  name: emailservice
  labels:
    app: emailservice
  type: ClusterIP
  port: 5000
  targetPort: 8080
