image:
  repository: preranamauryaa/microservice-checkoutservice
  tag: latest

serviceAccount:
  name: checkoutservice

namespace:
  name: checkoutservice

deployment:
  name: checkoutservice
  labels:
    app: checkoutservice
  container:
    name: server
    imagePullPolicy: Always
    env:
      PORT: "5050"
      PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
      SHIPPING_SERVICE_ADDR: "shippingservice:50051"
      PAYMENT_SERVICE_ADDR: "paymentservice:50051"
      EMAIL_SERVICE_ADDR: "emailservice:5000"
      CURRENCY_SERVICE_ADDR: "currencyservice:7000"
      CART_SERVICE_ADDR: "cartservice:7070"
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  readinessProbe:
    grpc:
      port: 5050
  livenessProbe:
    grpc:
      port: 5050

service:
  name: checkoutservice
  labels:
    app: checkoutservice
  type: ClusterIP
  port: 5050
  targetPort: 5050
