# Default values for checkoutservice
#global
name: checkoutservice
namespace: checkoutservice

replicaCount: 1

image:
  repository: preranamauryaa/microservice-checkoutservice
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5050
  targetPort: 5050

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

env:
  - name: PORT
    value: "5050"
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice:3550"
  - name: SHIPPING_SERVICE_ADDR
    value: "shippingservice:50051"
  - name: PAYMENT_SERVICE_ADDR
    value: "paymentservice:50051"
  - name: EMAIL_SERVICE_ADDR
    value: "emailservice:5000"
  - name: CURRENCY_SERVICE_ADDR
    value: "currencyservice:7000"
  - name: CART_SERVICE_ADDR
    value: "cartservice:7070"
