# Default values for the emailservice Helm chart
#global
name: emailservice
namespace: emailservice

replicaCount: 1
image:
  repository: preranamauryaa/microservice-emailservice
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

env:
  - name: PORT
    value: "8080"
  - name: DISABLE_PROFILER
    value: "1"

readinessProbe:
  periodSeconds: 5
  grpcPort: 8080

livenessProbe:
  periodSeconds: 5
  grpcPort: 8080
