apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.labels.app }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.labels.app }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        fsGroup: {{ .Values.deployment.securityContext.fsGroup }}
        runAsGroup: {{ .Values.deployment.securityContext.runAsGroup }}
        runAsNonRoot: {{ .Values.deployment.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.deployment.securityContext.runAsUser }}
      containers:
        - name: {{ .Values.deployment.container.name }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.deployment.container.imagePullPolicy }}
          ports:
          - containerPort: {{ .Values.deployment.container.port }}
          env:
          - name: PORT
            value: "{{ .Values.deployment.container.port }}"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice:3550"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice:7000"
          - name: CART_SERVICE_ADDR
            value: "cartservice:7070"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "recommendationservice:8080"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice:50051"
          - name: CHECKOUT_SERVICE_ADDR
            value: "checkoutservice:5050"
          - name: AD_SERVICE_ADDR
            value: "adservice:9555"
          - name: SHOPPING_ASSISTANT_SERVICE_ADDR
            value: "shoppingassistantservice:80"
          - name: ENABLE_PROFILER
            value: "0"
          resources:
            requests:
              cpu: {{ .Values.deployment.container.resources.requests.cpu }}
              memory: {{ .Values.deployment.container.resources.requests.memory }}
            limits:
              cpu: {{ .Values.deployment.container.resources.limits.cpu }}
              memory: {{ .Values.deployment.container.resources.limits.memory }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.deployment.probes.readiness.initialDelaySeconds }}
            httpGet:
              path: {{ .Values.deployment.probes.readiness.httpGet.path }}
              port: {{ .Values.deployment.probes.readiness.httpGet.port }}
              httpHeaders: {{ .Values.deployment.probes.readiness.httpGet.httpHeaders }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.deployment.probes.liveness.initialDelaySeconds }}
            httpGet:
              path: {{ .Values.deployment.probes.liveness.httpGet.path }}
              port: {{ .Values.deployment.probes.liveness.httpGet.port }}
              httpHeaders: {{ .Values.deployment.probes.liveness.httpGet.httpHeaders }}
