image:
  repository: preranamauryaa/microservice-recommendationservice
  tag: latest

serviceAccount:
  name: recommendationservice

deployment:
  name: recommendationservice
  labels:
    app: recommendationservice
  container:
    name: server
    imagePullPolicy: Always
    port: 8080
    resources:
      requests:
        cpu: 100m
        memory: 220Mi
      limits:
        cpu: 200m
        memory: 450Mi
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  readinessProbe:
    grpc:
      port: 8080
  livenessProbe:
    grpc:
      port: 8080

service:
  name: recommendationservice
  labels:
    app: recommendationservice
  type: ClusterIP
  port: 8080
  targetPort: 8080
