# Default values for productcatalogservice
# global
name: productcatalogservice
namespace: productcatalogservice

replicaCount: 1

image:
  repository: preranamauryaa/microservice-productcatalogservice
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3550
  targetPort: 3550

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

terminationGracePeriodSeconds: 5

env:
  - name: PORT
    value: "3550"
  - name: DISABLE_PROFILER
    value: "1"
